language: php

matrix:
  include:
    # LARAVEL 5.5
    - php: 7.0
      env: LARAVEL_VERSION=55
    - php: 7.1
      env: LARAVEL_VERSION=55
    - php: 7.2
      env: LARAVEL_VERSION=55
    # LARAVEL 5.6
    - php: 7.1
      env: LARAVEL_VERSION=56
    - php: 7.2
      env: LARAVEL_VERSION=56
    - php: 7.3
      env: LARAVEL_VERSION=56
    # LARAVEL 5.7
    - php: 7.1
      env: LARAVEL_VERSION=57
    - php: 7.2
      env: LARAVEL_VERSION=57
    - php: 7.3
      env: LARAVEL_VERSION=57

before_script:
  - travis_retry composer self-update -q
  - chmod +x ./build/**/*.sh

script:
  - ./build/${LARAVEL_VERSION}/build.sh

branches:
  only:
    - master
    - stable

after_success:
  - travis_retry php vendor/bin/coveralls -v
